services:
  knowledge-nexus:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knowledge-nexus
    restart: unless-stopped
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./graph_rag:/app/graph_rag
      - ./main.py:/app/main.py
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NOTION_API_KEY=${NOTION_API_KEY}
      - NOTION_ROOT_PAGE_ID=${NOTION_ROOT_PAGE_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      neo4j:
        condition: service_healthy

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins
    healthcheck:
      test: ["CMD", "wget", "http://localhost:7474/"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 3s
