# Example config.yaml
notion_api:
  base_url: https://api.notion.com/v1/
  version: "2022-06-28"
  timeout: 60
  page_max_depth: 100
  create_unprocessed_graph_nodes: true

pocket_api:
  base_url: https://getpocket.com/v3/

llm:
  model: gpt-3.5-turbo
  temperature: 0.7
  max_tokens: 150

cache:
  enabled: true
  path_to_cache: cache/
