neo4j:
  uri: ${NEO4J_URI:bolt://localhost:7687}
  user: ${NEO4J_USER:neo4j}
  password: ${NEO4J_PASSWORD:neo4j}

notion_api:
  base_url: https://api.notion.com/v1/
  version: "2022-06-28"
  timeout: 60
  cache_ttl_seconds: 3600
  cache_path:
  api_key: ${NOTION_API_KEY}
  #  processing strategy
  page_max_depth: 200
  add_archived_page_nodes: false
  add_removed_page_nodes: false
  create_unprocessed_graph_nodes: false
  recursive_process_reference_pages: true
  markdown_parser_options:
    indent: "  "
    excluded_property_types: [
      "created_by",
      "last_edited_by",
      "last_edited_time",
      "unique_id",
      "verification"
    ]
    excluded_block_types: [
      "breadcrumb",
      "column_list",
      "column",
      "table_of_contents"
    ]

pocket_api:
  base_url: https://getpocket.com/v3/

llm:
  api_key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
  temperature: 0.7
  max_tokens: 150

cache:
  enabled: true
  path: cache/
#  set 1 day TTL in seconds
  ttl_seconds: 86400

web_parser:
  timeout: 10
