flowchart TB

    subgraph IngestionApp ["Ingestion Architecture"]
        direction LR
	    subgraph Ingestion ["Pluggable Data providers"]
	        direction TB
	        NotionProvider>"Notion Provider"]
	        TodoistProvider>"Todoist Provider"]
	        WebProvider>"Web Scrapper"]
	        CustomProviders@{ shape: processes, label: "Custom Providers" }
	    end

	    subgraph ProcessingPipeline ["Processing Pipeline"]
	        direction LR
	        Chunking[["Content Chunking"]]
	        EntityExtraction[["Entity Extraction"]]
	        TopicModeling[["Topic Modeling"]]
	        Clusterization[["Clusterization"]]
	        Embedding[["Embedding Generation"]]
	    end

	    UnifiedData[/"Raw Graph
	    (based on data structure)"/]

	    KnowledgeGraph[/"Enriched Knowledge Graph
	    (structure + semantic relations)"/]

    end
    subgraph QnAApp ["Q&A Architecture"]
        QueryProcessor["Query Processor"]
        StreamlitInterface["Streamlit Interface"]
    end

    subgraph DataSources ["External Data Sources"]
        Notion["Notion API"]
        APIs@{ shape: processes, label: "Other APIs/resources" }
    end

    subgraph Flow ["User Flow"]
	    User("👤 2. User")
	    Prepare("🧠📩 1. Prepare knowledge")
    end
    Neo4j[(Neo4j Graph Database)]


    %% Connections
    Prepare-->|Initiate Data Ingestion|Ingestion
    DataSources-->|Fetching Data|Ingestion
    Ingestion-->UnifiedData
    UnifiedData-->ProcessingPipeline
    ProcessingPipeline-->KnowledgeGraph
    KnowledgeGraph-->Neo4j
    QueryProcessor<-->Neo4j
    StreamlitInterface<-->QueryProcessor
    User<-->|Asks question|StreamlitInterface


    %% Legend
    subgraph Legend
        %% direction LR
        Implemented["Implemented"]
        Future["Planned"]
    end

    %% Styling
    classDef implemented fill:#90EE90,stroke:#333,color:#000,stroke-width:2px;
    classDef future fill:#FFB6C1,stroke:#333,color:#000,stroke-width:2px,stroke-dasharray: 5 5;

    classDef transparent fill:#E6E6FA,fill-opacity:0.1,stroke:#333,stroke-width:5px;

    class Prepare,Notion,NotionProvider,Chunking,Embedding,QueryProcessor,KnowledgeGraph,Neo4j,User,UnifiedData,StreamlitInterface implemented;
    class Todoist,TodoistProvider,APIs,CustomProviders,Web,WebProvider,EntityExtraction,TopicModeling,Clusterization future;
    class Implemented implemented;
    class Future future;
    class IngestionApp,QnAApp transparent;