name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run linter
        run: |
          pip install flake8
          flake8 --extend-ignore E501,W291 graph_rag --exit-zero

      - name: Run tests
        run: |
          pytest --cov=graph_rag
        env:
          PYTHONPATH: .
